### 행렬의 고유값(eigenvalue)과 고유벡터(eigenvector)
#### 행렬의 고유값이란 A\*x = a\*x 방정식의 스칼라 해 a이다 .여기서 A는 2차원 행렬이고 x는 1차원 벡터이다(a가 고유값)
#### 고유벡터는 선형 변환이 일어나도 방향이 변하지 않는 벡터(2차원에서 1차원으로 축소하여도 고유한 성질을 그대로 지님)
#### PCA나 SVD와 같은  차원 축소 알고리즘에 이용된다

In [2]:
import numpy as np
A = np.array([[3, -2],
              [1, 0]])
print("A\n", A)
# print("Eigenvalues : ", np.linalg.eigvals(A)) # 고유값
eigenvalues, eigenvectors = np.linalg.eig(A)
print("고유값(a) : ", eigenvalues)
print("고유벡터(x) : \n", eigenvectors)

A
 [[ 3 -2]
 [ 1  0]]
고유값(a) :  [2. 1.]
고유벡터(x) : 
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
# A*x = a*x 방정식에 대입하여 결과 값 비교
A_dot_x = np.dot(A, eigenvectors)
print('A*x:\n',A_dot_x)

a_dot_x_0 = eigenvalues[0] * eigenvectors[:,0] # 0번 열 , 고유값은 스칼라이므로 일반 곱셈
a_dot_x_1 = eigenvalues[1] * eigenvectors[:,1] # 1번 열 , 고유값은 스칼라이므로 일반 곱셈
print('a*x 0번 열:\n',a_dot_x_0.reshape(2,-1))
print('a*x 1번 열:\n',a_dot_x_1.reshape(2,-1))

A*x:
 [[1.78885438 0.70710678]
 [0.89442719 0.70710678]]
a*x 0번 열:
 [[1.78885438]
 [0.89442719]]
a*x 1번 열:
 [[0.70710678]
 [0.70710678]]


In [5]:
for i in range(len(eigenvalues)):
    print("Left", np.dot(A, eigenvectors[:,i]))
    print("Right", eigenvalues[i] * eigenvectors[:,i])

Left [1.78885438 0.89442719]
Right [1.78885438 0.89442719]
Left [0.70710678 0.70710678]
Right [0.70710678 0.70710678]


## SVD(Singular Value Decomposition, 특잇값분해) 
#### 임의의 행렬 X를 U,S,V 세개의 행렬의 곱으로 분해
- U 와 V는 직교행렬(orthogonal matrix)이고 그 열 벡터는 서로 직교한다 <br>
- U는 $ (X)*(X^T)$를 고유값 분해해서 얻은 직교 행렬이며, V는 $(X^T)*(X)$를 고유값 분해해서 얻은 직교 행렬입니다
- 직교 행렬은 $Q^T*Q = Q*Q^T = E(단위행렬), $  즉  Q<sup>T</sup> = Q<sup>-1</sup>  (전치 행렬이 역행렬과 같은 행렬)
- S 는 대각행렬(diagonal matrix, 대각 성분 외에는 모두 0인 행렬)이다,시그마라고 읽는다

 https://angeloyeo.github.io/2019/08/01/SVD.html

In [4]:
import numpy as np

# X = np.array([[3,6],
#               [2,3],
#               [0,0],
#               [0,0]])

X = np.array([[3,6,1],
              [2,3,4],
              [0,0,0]])
print(X,X.shape)

[[3 6 1]
 [2 3 4]
 [0 0 0]] (3, 3)


In [5]:
# numpy svd() 특잇값분해 함수 사용
U, S, VT = np.linalg.svd(X) 
print('U:\n',U)
print('S:\n',S)
print('VT:\n',VT)

U:
 [[-0.80326882 -0.59561665  0.        ]
 [-0.59561665  0.80326882  0.        ]
 [ 0.          0.          1.        ]]
S:
 [8.17078636 2.87023522 0.        ]
VT:
 [[-0.44072132 -0.80854677 -0.38989337]
 [-0.06282144 -0.40550455  0.91193175]
 [ 0.89544301 -0.42640143 -0.12792043]]


In [6]:
# X와 X의 전치행렬의 내적곱 : (4,2) * (2,4) = (4,4)
u = np.dot(X , X.T)
print(X)
print(X.T)
u

[[3 6 1]
 [2 3 4]
 [0 0 0]]
[[3 2 0]
 [6 3 0]
 [1 4 0]]


array([[46, 28,  0],
       [28, 29,  0],
       [ 0,  0,  0]])

In [35]:
U_eigenvalues ,U_eigenvector= np.linalg.eig(u)  # 'eigen' : 아이건으로 발음
print('U 고유값:',U_eigenvalues)
print('U 고유벡터:\n',U_eigenvector) # 값이 약간 다름, numpy버전이나 OS에따라 축의 순서가 다르나 차원 축소 효과는 동일

U 고유값: [-1.  1.  1.]
U 고유벡터:
 [[-0.94954432  0.31363289  0.        ]
 [-0.31363289 -0.94954432  0.        ]
 [ 0.          0.          1.        ]]


In [36]:
print(np.__version__)


'1.17.0'

In [8]:
# X의 전치행렬과 X의 내적곱 : (2, 4) * (4,2) = (2,2)
v = np.dot(X.T , X)
v

array([[13, 24, 11],
       [24, 45, 18],
       [11, 18, 17]])

In [9]:
V_eigenvalues ,V_eigenvector = np.linalg.eig(v)
print('V 고유값:', V_eigenvalues)
print('V 고유벡터:\n',V_eigenvector) # 값이 위와 약간 다름,차원 축소 효과는 동일

V 고유값: [ 6.67617498e+01 -2.57619311e-15  8.23825022e+00]
V 고유벡터:
 [[ 0.44072132  0.89544301 -0.06282144]
 [ 0.80854677 -0.42640143 -0.40550455]
 [ 0.38989337 -0.12792043  0.91193175]]


In [10]:
u, s, vh = np.linalg.svd(X)

In [11]:
X

array([[3, 6, 1],
       [2, 3, 4],
       [0, 0, 0]])

In [12]:
u

array([[-0.80326882, -0.59561665,  0.        ],
       [-0.59561665,  0.80326882,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [13]:
s

array([8.17078636, 2.87023522, 0.        ])

In [14]:
S = np.diag(s) # (3,3))  # 대각 행렬로 변환
S

array([[8.17078636, 0.        , 0.        ],
       [0.        , 2.87023522, 0.        ],
       [0.        , 0.        , 0.        ]])

In [15]:
# np.diag() : 대각행렬(diagonal matrix) 생성
x = np.arange(9).reshape(3, 3)
print(x)
print(np.diag(x))    # [0 4 8] , 0번 열에서 시작하는 대각선 요소만 추출
print(np.diag(x,0))  # [0 4 8] , 0번 열에서 시작하는 대각선 요소만 추출, 위와 동일
print(np.diag(x,1))  # [1 5], 1번 열에서 시작하는 대각선 요소만 추출
print(np.diag(x,2))  # [2] , 2번 열에서 시작하는 대각선 요소만 추출

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[0 4 8]
[1 5]
[2]


In [16]:
print(np.diag([0,4,8])) # [0 4 8]을 이용하여 대각 행렬 생성
print(np.diag([0, 4, 8],0))
print(np.diag([0, 4, 8],1))
print(np.diag([0, 4, 8],2))

[[0 0 0]
 [0 4 0]
 [0 0 8]]
[[0 0 0]
 [0 4 0]
 [0 0 8]]
[[0 0 0 0]
 [0 0 4 0]
 [0 0 0 8]
 [0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 4 0]
 [0 0 0 0 8]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [17]:
vh

array([[-0.44072132, -0.80854677, -0.38989337],
       [-0.06282144, -0.40550455,  0.91193175],
       [ 0.89544301, -0.42640143, -0.12792043]])

In [18]:
np.dot(np.dot(u, S), vh)

array([[3., 6., 1.],
       [2., 3., 4.],
       [0., 0., 0.]])

In [20]:
from numpy.linalg import svd

A = np.array([[3, -1],
              [1, 3], 
              [1, 1]])
U, S, VT = svd(A)

In [21]:
U

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -1.94289029e-16,  9.12870929e-01]])

In [22]:
S

array([3.46410162, 3.16227766])

In [23]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

###  NumPy 선형대수 함수 (Linear Algebra)

- 단위행렬,항등행렬 (Unit matrix,Identity matrix): np.eye(n)
- 대각행렬 (Diagonal matrix): np.diag(x)
- 내적 (Dot product, Inner product): np.dot(a, b)
- 대각합 (Trace): np.trace(x)
- 행렬식 (Matrix Determinant): np.linalg.det(x)
- 역행렬 (Inverse of a matrix): np.linalg.inv(x)
- 고유값 (Eigenvalue), 고유벡터 (Eigenvector): w, v = np.linalg.eig(x)
- 특이값 분해 (Singular Value Decomposition): u, s, vh = np.linalg.svd(A)
- 연립방정식 해 풀기 (Solve a linear matrix equation): np.linalg.solve(a, b)
- 최소자승 해 풀기 (Compute the Least-squares solution): m, c = np.linalg.lstsq(A, y, rcond=None)[0]

   https://rfriend.tistory.com/tag/np.diag(x) 

In [24]:
# np.diag() : 대각행렬(diagonal matrix) 생성
print(np.diag(S, 1))
np.diag(S, 1)[:, 1:]

[[0.         3.46410162 0.        ]
 [0.         0.         3.16227766]
 [0.         0.         0.        ]]


array([[3.46410162, 0.        ],
       [0.        , 3.16227766],
       [0.        , 0.        ]])

In [25]:
# 파이썬 버전 3.5 에서 '@' 연산자는 행렬의 내적 곱셈을 위한 중위 연산자로 추가되었다
a = np.array([[1,2],
              [3,4]])
print(a)

print(a@a)
print(np.dot(a,a))

[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [26]:
U @ np.diag(S, 1)[:, 1:] @ VT

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

In [27]:
U2, S2, VT2 = svd(A, full_matrices=False)

In [28]:
U2

array([[-4.08248290e-01,  8.94427191e-01],
       [-8.16496581e-01, -4.47213595e-01],
       [-4.08248290e-01, -1.94289029e-16]])

In [29]:
S2

array([3.46410162, 3.16227766])

In [30]:
VT2

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [31]:
np.diag(S2) 

array([[3.46410162, 0.        ],
       [0.        , 3.16227766]])

In [32]:
U2 @ np.diag(S2) @ VT2

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

In [33]:
x = np.diag(np.arange(4))
print(x)
print(np.dot(x,x))
print(x @ x)

[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]
[[0 0 0 0]
 [0 1 0 0]
 [0 0 4 0]
 [0 0 0 9]]
[[0 0 0 0]
 [0 1 0 0]
 [0 0 4 0]
 [0 0 0 9]]


In [34]:
a = np.array([1,2])
b = np.array([3,4])
print(a @ b)
np.dot(a,b)

11


11