In [1]:
from mynlp import preprocess, create_co_matrix, cos_similarity, most_similar
import numpy as np
import matplotlib.pyplot as plt

[0 1 2 3 4 1 5 6]
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}
[0 1 0 0 0 0 0 0]
[0 1 0 1 0 0 0 0]
[0 1 0 1 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 1 0 0 0]
0.7071067691154799
[0 1 0 1 0 0 0]
[0 1 0 0 0 0 1]
0.49999999292893216

[query] you
 goodbye: 0.7071067691154799
 i: 0.7071067691154799
 hello: 0.7071067691154799
 say: 0.0
 and: 0.0


In [2]:
# ppmi 계산을 함수로 구현 
def ppmi(C, verbose=False, eps = 1e-8):
    M = np.zeros_like(C, dtype=np.float32)
    N = np.sum(C)
    S = np.sum(C, axis=0)
    total = C.shape[0] * C.shape[1]
    cnt = 0

    for i in range(C.shape[0]):
        for j in range(C.shape[1]):
            pmi = np.log2(C[i, j] * N / (S[i]*S[j]) + eps)
            M[i, j] = max(0, pmi)

            if verbose:
                cnt += 1
                if cnt % (total//100) == 0:
                    print('%.1f%% 완료' % (100*cnt/total))
    return M

In [3]:
# from dataset import ptb

# corpus, word_to_id, id_to_word = ptb.load_data('train')

# print('말뭉치 크기:', len(corpus), corpus.shape)  # (929589,)
# print('corpus[:30]:', corpus[:30])
# print()
# print('id_to_word[0]:', id_to_word[0])
# print('id_to_word[1]:', id_to_word[1])
# print('id_to_word[2]:', id_to_word[2])
# print()
# print("word_to_id['car']:", word_to_id['car'])
# print("word_to_id['happy']:", word_to_id['happy'])
# print("word_to_id['lexus']:", word_to_id['lexus'])

# 실습과제 답안 구현 부분

In [4]:
# [실습 과제]  : PPMI 단어의 유사도 측정

# 1. 아래 문장에 사용된 단어를 PTB데이터셋을 PPMI 와 SVD 차원 축소 기법을 사용하여 만든 벡터에 넣어 각 단어들의 유사도를 측정하여 출력해보세요

# text = "The black cat ran so fast that the white mouse could not run away."

# 주어진 text를 말뭉치로 변환한다
# 마침표는 삭제한다
# 유사도 출력 코드는 for 문을 사용하여 반복한다

# 2. WordNet을 사용한 경로 거리 기반 유사도 (Path Distance Similarity)값과 비교하여 보세요
# 'black'과 'white'의 유사도와 'cat'과 'mouse'의 유사도만 다음 3개의 방법으로 비교해 본다
# - 경로 거리 기반 유사도 (Path Distance Similarity)
# - 우 팔머 유사도 (Wu-Palmer Similarity)
# - 리콕 초도로우 유사도(Leacock Chordorow Similarity)

In [5]:
# PTB 데이터셋으로 PPMI 얻기

from dataset import ptb


window_size = 2
wordvec_size = 100

corpus, word_to_id, id_to_word = ptb.load_data('train')
vocab_size = len(word_to_id)
print('동시발생 수 계산 ...')
C = create_co_matrix(corpus, vocab_size, window_size)
print('PPMI 계산 ...')
W = ppmi(C, verbose=True)

동시발생 수 계산 ...
PPMI 계산 ...


C:\ProgramData\Anaconda3\envs\tf20\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in long_scalars
  # This is added back by InteractiveShellApp.init_path()
C:\ProgramData\Anaconda3\envs\tf20\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in log2
  # This is added back by InteractiveShellApp.init_path()


1.0% 완료
2.0% 완료
3.0% 완료
4.0% 완료
5.0% 완료
6.0% 완료
7.0% 완료
8.0% 완료
9.0% 완료
10.0% 완료
11.0% 완료
12.0% 완료
13.0% 완료
14.0% 완료
15.0% 완료
16.0% 완료
17.0% 완료
18.0% 완료
19.0% 완료
20.0% 완료
21.0% 완료
22.0% 완료
23.0% 완료
24.0% 완료
25.0% 완료
26.0% 완료
27.0% 완료
28.0% 완료
29.0% 완료
30.0% 완료
31.0% 완료
32.0% 완료
33.0% 완료
34.0% 완료
35.0% 완료
36.0% 완료
37.0% 완료
38.0% 완료
39.0% 완료
40.0% 완료
41.0% 완료
42.0% 완료
43.0% 완료
44.0% 완료
45.0% 완료
46.0% 완료
47.0% 완료
48.0% 완료
49.0% 완료
50.0% 완료
51.0% 완료
52.0% 완료
53.0% 완료
54.0% 완료
55.0% 완료
56.0% 완료
57.0% 완료
58.0% 완료
59.0% 완료
60.0% 완료
61.0% 완료
62.0% 완료
63.0% 완료
64.0% 완료
65.0% 완료
66.0% 완료
67.0% 완료
68.0% 완료
69.0% 완료
70.0% 완료
71.0% 완료
72.0% 완료
73.0% 완료
74.0% 완료
75.0% 완료
76.0% 완료
77.0% 완료
78.0% 완료
79.0% 완료
80.0% 완료
81.0% 완료
82.0% 완료
83.0% 완료
84.0% 완료
85.0% 완료
86.0% 완료
87.0% 완료
88.0% 완료
89.0% 완료
90.0% 완료
91.0% 완료
92.0% 완료
93.0% 완료
94.0% 완료
95.0% 완료
96.0% 완료
97.0% 완료
98.0% 완료
99.0% 완료
100.0% 완료


In [6]:
print('calculating SVD ...')

# truncated SVD : 속도가 빠르다, random 사용으로 매번 다른 결과 출력
from sklearn.utils.extmath import randomized_svd
U, S, V = randomized_svd(W, n_components=wordvec_size, n_iter=5,
                         random_state=None)

word_vecs = U[:, :wordvec_size]  # 100개로 차원 축소
print(word_vecs.shape) # (1000,100)
word_vecs

calculating SVD ...
(10000, 100)


array([[-7.1707566e-12,  5.1619224e-08, -4.1907410e-07, ...,
        -3.8067374e-05,  1.2358902e-04, -7.4633238e-07],
       [-1.4708361e-11,  1.2856992e-07, -1.1112376e-07, ...,
        -6.0247141e-05,  1.7635472e-04, -2.3392754e-06],
       [-5.5097797e-12, -2.0442064e-09,  1.1041527e-08, ...,
        -8.3547144e-05,  2.3952904e-04, -4.1339858e-06],
       ...,
       [ 4.4260337e-03, -6.4803013e-03,  1.1453294e-02, ...,
         1.4470930e-02, -3.2744058e-03,  4.6140300e-03],
       [ 2.4589046e-03, -4.9205646e-03,  8.0249971e-03, ...,
         1.0419410e-03,  4.4056461e-03,  4.0153073e-04],
       [ 3.8884017e-03, -7.8423517e-03,  8.0783209e-03, ...,
        -2.1364212e-03, -2.3151156e-03,  1.5917586e-02]], dtype=float32)

In [7]:
# most_similar('she', word_to_id, id_to_word, word_vecs, top=5)
# most_similar('was', word_to_id, id_to_word, word_vecs, top=5)
# most_similar('much', word_to_id, id_to_word, word_vecs, top=5)
# most_similar('scared', word_to_id, id_to_word, word_vecs, top=5)
# most_similar('because', word_to_id, id_to_word, word_vecs, top=5)
# most_similar('the', word_to_id, id_to_word, word_vecs, top=5)
# most_similar('lion', word_to_id, id_to_word, word_vecs, top=5)
# most_similar('was', word_to_id, id_to_word, word_vecs, top=5)
# most_similar('too', word_to_id, id_to_word, word_vecs, top=5)
# most_similar('big', word_to_id, id_to_word, word_vecs, top=5)

In [8]:
text = 'The black cat ran so fast that the white mouse could not run away.'
text = text.lower()
text = text.replace('.', '')
words = text.split(' ')

# corpus, word_to_id, id_to_word = preprocess(text)

words

['the',
 'black',
 'cat',
 'ran',
 'so',
 'fast',
 'that',
 'the',
 'white',
 'mouse',
 'could',
 'not',
 'run',
 'away']

In [9]:
for query in words:
    most_similar(query, word_to_id, id_to_word, word_vecs, top=5)


[query] the
 of: 0.6370799541473389
 a: 0.6024384498596191
 in: 0.5321652293205261
 this: 0.4323727488517761
 <unk>: 0.43163061141967773

[query] black
 hispanic: 0.4898976981639862
 white: 0.4879007339477539
 young: 0.4864444136619568
 women: 0.48602789640426636
 activist: 0.4495448172092438

[query] cat
 test: 0.5497627258300781
 lumpur: 0.5094209909439087
 bars: 0.48442214727401733
 kuala: 0.45799267292022705
 holidays: 0.4501901865005493

[query] ran
 turned: 0.5427704453468323
 throws: 0.523361325263977
 carpeting: 0.5218486189842224
 interior: 0.5037709474563599
 pulls: 0.5019594430923462

[query] so
 too: 0.5818270444869995
 far: 0.42303043603897095
 quite: 0.39934849739074707
 much: 0.3794543147087097
 more: 0.3670775890350342

[query] fast
 hard: 0.5779397487640381
 attractive: 0.5157228112220764
 accessible: 0.4956439435482025
 quickly: 0.46727269887924194
 risky: 0.43322256207466125

[query] that
 he: 0.5803117156028748
 it: 0.4878789186477661
 they: 0.44563642144203186
 th

In [10]:
# 실습 과제 2번

In [11]:
from nltk.corpus import wordnet

# syn = wordnet.synsets('black')
# print(syn)
black = wordnet.synset('black.n.01')
white = wordnet.synset('white.n.01')

# 경로 유사도
print('black: [path]', black.path_similarity(white))

# Wu-Palmer Similarit
print('black: [wup]', black.wup_similarity(white))

# Leacock Chordorow Similarity
print('black: [lch]', black.lch_similarity(white))

black: [path] 0.08333333333333333
black: [wup] 0.15384615384615385
black: [lch] 1.1526795099383855


In [12]:
# syn = wordnet.synsets('cat')
# print(syn)
cat = wordnet.synset('cat.n.01')
mouse = wordnet.synset('mouse.n.01')

# 경로 유사도
print('cat: [path]', black.path_similarity(mouse))

# Wu-Palmer Similarit
print('cat: [wup]', black.wup_similarity(mouse))

# Leacock Chordorow Similarity
print('cat: [lch]', black.lch_similarity(mouse))

cat: [path] 0.05
cat: [wup] 0.09523809523809523
cat: [lch] 0.6418538861723948


In [13]:
#  정규표현식 사용 자동화 구현
import re
from nltk.corpus import wordnet

# 표제어를 정규표현식으로 검출
def get_match(word) :
    # r = r"black.n.01"
    r = r"^(%s)+(.)([a-z]+)(.)(01)$"%word
    p = re.compile(r, re.I)

    syn = [ syn.name() for syn in wordnet.synsets(word) ]
    # print(syn) 

    for s in syn:
        # print(s)
        match = p.match(s,0)
        if match :
            #print(match.group())
            break
    if match.group():
        return match.group()

# 검출된 두 단어의 표제어로 유사도 출력
def get_wordnet_similarity(word1,word2):
    
    word1_match = get_match(word1)
    word2_match = get_match(word2)

    word1_syn = wordnet.synset(word1_match)
    word2_syn = wordnet.synset(word2_match)
    print('-'*50)

    # 경로 유사도
    print('%s - %s [path] : %f'%(word1,word2, word1_syn.path_similarity(word2_syn)))
    
    # Wu-Palmer Similarity
    print('%s - %s [wup] :'%(word1,word2), word1_syn.wup_similarity(word2_syn))

    # Leacock Chordorow Similarity
    print('%s - %s [lch] :'%(word1,word2), word1_syn.lch_similarity(word2_syn))


# 함수 호출   
get_wordnet_similarity('black', 'white')
get_wordnet_similarity('cat', 'mouse')
get_wordnet_similarity('fast', 'run')

--------------------------------------------------
black - white [path] : 0.083333
black - white [wup] : 0.15384615384615385
black - white [lch] : 1.1526795099383855
--------------------------------------------------
cat - mouse [path] : 0.166667
cat - mouse [wup] : 0.8148148148148148
cat - mouse [lch] : 1.845826690498331
--------------------------------------------------
fast - run [path] : 0.083333
fast - run [wup] : 0.47619047619047616
fast - run [lch] : 1.1526795099383855
