# Keras layer 추가 정리
https://www.tensorflow.org/api_docs/python/tf/keras/layers

In [1]:
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Permute, Dot, dot, Add, add, Concatenate, concatenate
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input, Activation
import tensorflow as tf
import numpy as np

## [1]  tf.keras.layers.Permute
#### 행과 열의 차원을 서로 바꾼다

<font size="4"> <pre> <b>  
        tf.keras.layers.Permute( 
             dims, **kwargs     
        )
</b> </pre>

In [2]:
X = np.arange(6).reshape(1,2,3)
print('X:\n',X)
permute = Permute((1, 2))
Y = permute(X)
print('Y:\n',Y.numpy())
# 변화 없음

X:
 [[[0 1 2]
  [3 4 5]]]
Y:
 [[[0 1 2]
  [3 4 5]]]


In [3]:
X = np.arange(6).reshape(1,2,3)
print('X:\n',X)
permute = Permute((2, 1))
Y = permute(X)
print('Y:\n',Y.numpy())
# 행(axis=1)과 열(axis=2)의 값이 서로 바뀜

X:
 [[[0 1 2]
  [3 4 5]]]
Y:
 [[[0 3]
  [1 4]
  [2 5]]]


In [4]:
model = Sequential()
model.add(Permute((2, 1), input_shape=(10, 64)))
model.summary()

# 출력 결과 shape이  (None, 64, 10)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
permute_2 (Permute)          (None, 64, 10)            0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


## [2]  tf.keras.layers.Dot
#### 두 개의 입력값으로 dot product(내적) 연산을 수행하는 layer
#### Matmul layer가 따로 없으므로 Dot으로 Matmul 연산 수행

<font size="4"> <pre> <b>  
        tf.keras.layers.Dot(
            axes, normalize=False, **kwargs
        )
        
        - axis = (x1_axis,x2_axis) # x1_axis의 shape과 x2_axis의 shape은 서로 동일해야 한다
</b> </pre>

In [5]:
X1 = np.arange(1*2*3).reshape((1,2,3))
print('X1:\n',X1)
X2 = np.arange(1*2*3).reshape((1,3,2))
print('X2:\n',X2)

D = np.dot(X1,X2)
print('D:\n',D,D.shape)  # (1, 2, 1, 2)

M = np.matmul(X1,X2)
print('M:\n',M,M.shape)  # (1, 2, 2)

Y1 = Dot(axes=(2, 1))([X1, X2])  # np.matmul(X1,X2) 과 동일한 결과
print('Y1:\n',Y1.numpy(),Y1.shape) # (1, 2, 2)

Y2 = Dot(axes=(1, 2))([X1, X2])  
print('Y2:\n',Y2.numpy(),Y2.shape) # (1, 3, 3)

# Y3 = Dot(axes=(1, 1))([X1, X2])  # ValueError
# Y4 = Dot(axes=(2, 2))([X1, X2])  # ValueError

X1:
 [[[0 1 2]
  [3 4 5]]]
X2:
 [[[0 1]
  [2 3]
  [4 5]]]
D:
 [[[[10 13]]

  [[28 40]]]] (1, 2, 1, 2)
M:
 [[[10 13]
  [28 40]]] (1, 2, 2)
Y1:
 [[[10 13]
  [28 40]]] (1, 2, 2)
Y2:
 [[[ 3  9 15]
  [ 4 14 24]
  [ 5 19 33]]] (1, 3, 3)


In [6]:
X1 = np.arange(1*2*3).reshape((1,2,3))
print('X1:\n',X1)
X2 = np.arange(1*4*3).reshape((1,4,3))
print('X2:\n',X2)

Y1 = Dot(axes=(2,2))([X1, X2]) 
print('Y1:\n',Y1.numpy(),Y1.shape) # (1, 2, 4)

Y2 = Dot(axes=-1)([X1, X2])   # axes=(2,2)와 동일한 결과
print('Y2:\n',Y2.numpy(),Y2.shape) # (1, 2, 4)

X1:
 [[[0 1 2]
  [3 4 5]]]
X2:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]
Y1:
 [[[  5  14  23  32]
  [ 14  50  86 122]]] (1, 2, 4)
Y2:
 [[[  5  14  23  32]
  [ 14  50  86 122]]] (1, 2, 4)


### - dot() function
<font size="4"> <pre> <b>  
    tf.keras.layers.dot(
        inputs, axes, normalize=False, **kwargs
    )
</b> </pre>

In [7]:
X1 = np.arange(1*2*3).reshape((1,2,3))
print('X1:\n',X1)
X2 = np.arange(1*2*3).reshape((1,3,2))
print('X2:\n',X2)

Y = dot([X1, X2],axes=(2,1))  # np.matmul(X1,X2) 과 동일한 결과
print('Y:\n',Y.numpy(),Y.shape) # (1, 2, 2)

# Y1 = dot([X1, X2],axes=(1,1))  # ValueError
# Y2 = dot([X1, X2],axes=(2,2))   # ValueError

X1:
 [[[0 1 2]
  [3 4 5]]]
X2:
 [[[0 1]
  [2 3]
  [4 5]]]
Y:
 [[[10 13]
  [28 40]]] (1, 2, 2)


In [8]:
X1 = np.arange(1*2*3).reshape((1,2,3))
print('X1:\n',X1)
X2 = np.arange(1*4*3).reshape((1,4,3))
print('X2:\n',X2)

Y1 = dot([X1, X2],axes=(2,2))  
print('Y1:\n',Y1.numpy(),Y1.shape) # (1, 2, 4)

Y2 = dot([X1, X2],axes=-1) # axes=(2,2)와 동일한 표현
print('Y2:\n',Y2.numpy(),Y2.shape) # (1, 2, 2)

X1:
 [[[0 1 2]
  [3 4 5]]]
X2:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]
Y1:
 [[[  5  14  23  32]
  [ 14  50  86 122]]] (1, 2, 4)
Y2:
 [[[  5  14  23  32]
  [ 14  50  86 122]]] (1, 2, 4)


In [9]:
X1 = np.arange(6).reshape(1, 3, 2)
print('X1:\n',X1)
X2 = np.arange(10, 16).reshape(1, 2, 3)
print('X2:\n',X2)
Y1 = np.dot(X1,X2)
print('Y1:\n',Y1,Y1.shape)
Y2 = np.matmul(X1,X2)
print('Y2:\n',Y2,Y2.shape)

X1:
 [[[0 1]
  [2 3]
  [4 5]]]
X2:
 [[[10 11 12]
  [13 14 15]]]
Y1:
 [[[[ 13  14  15]]

  [[ 59  64  69]]

  [[105 114 123]]]] (1, 3, 1, 3)
Y2:
 [[[ 13  14  15]
  [ 59  64  69]
  [105 114 123]]] (1, 3, 3)


In [10]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
c = np.dot(a, b)
c.shape

(3, 4, 5, 5, 4, 3)

### Numpy dot()과 matmul() 함수의 3차원 배열 연산 시 차이
https://m.blog.naver.com/PostView.nhn?blogId=cjh226&logNo=221356884894&proxyReferer=https:%2F%2Fwww.google.com%2F

### [1]  np.dot()
<font size="4"> <pre> <b>  
    A.shape # (a1, a2, <font color='red'>a3</font>)
    B.shape # (b1, <font color='red'>b2</font>, b3)
    --> <font color='red'>a3==b2</font>   <font color='green'># dot 연산이 가능한 조건 </font>
    C = np.dot(A,B)
    print(C.shape)
    (a1, a2, b1, b3)  # 연산 결과가 4차원
    
    동일 연산식:
    C[i,j,k,m] = np.sum(A[i,j,:] * B[k,:,m])
</b> </pre>   
 

In [11]:
# np.dot() 연산 : 3차원 배열끼리 연산 결과 4차원 배열 생성 

X1 = np.arange(1*2*3).reshape((1,2,3))
print('X1:\n',X1)
X2 = np.arange(1*2*3).reshape((1,3,2))
print('X2:\n',X2)
Y1 = np.dot(X1,X2)
print('Y1:\n',Y1,Y1.shape)  # (1, 2, 1, 2)

# 동일한 결과의 연산
a1,a2,b1,b3 = X1.shape[0],X1.shape[1],X2.shape[0],X2.shape[2]
Y2 = np.empty(a1*a2*b1*b3).reshape((a1,a2,b1,b3))
for i in range(a1):
    for j in range(a2):
        for k in range(b1):
            for l in range(b3):
                Y2[i,j,k,l] = np.sum(X1[i,j,:] * X2[k,:,l])
                
print('Y2:\n',Y2, Y2.shape)  # (1, 2, 1, 2)

X1:
 [[[0 1 2]
  [3 4 5]]]
X2:
 [[[0 1]
  [2 3]
  [4 5]]]
Y1:
 [[[[10 13]]

  [[28 40]]]] (1, 2, 1, 2)
Y2:
 [[[[10. 13.]]

  [[28. 40.]]]] (1, 2, 1, 2)


### [2]  np.matmul()   
<font size="4"> <pre> <b>  
    A.shape # (<font color='blue'>a1</font>, a2, <font color='red'>a3</font>)
    B.shape # (<font color='blue'>b1</font>, <font color='red'>b2</font>, b3)
    --> <font color='red'> (a1==b1) and (a3==b2)</font> <font color='green'># matmul 연산이 가능한 조건 </font>
    C = np.matmul(A,B)
    print(C.shape)
    (a1, a2, b3)    # 연산 결과가 3차원
    
    동일 연산식:
    C[i,j,k] = np.sum(A[i,j,:] * B[i,:,k])
</b> </pre>

In [12]:
# np.matmu() 연산  : 3차원 배열끼리 연산 결과 3차원 배열 생성 
X1 = np.arange(1*2*3).reshape((1,2,3))
print('X1:\n',X1)
X2 = np.arange(1*2*3).reshape((1,3,2))
print('X2:\n',X2)
Y1 = np.matmul(X1,X2)
print('Y1:\n',Y1,Y1.shape)  # (1, 2, 2)

# 동일한 결과의 연산
a1,a2,b3 = X1.shape[0],X1.shape[1],X2.shape[2]
Y2 = np.empty(a1*a2*b3).reshape((a1,a2,b3))
for i in range(a1):
    for j in range(a2):
        for k in range(b3):
                Y2[i,j,k] = np.sum(X1[i,j,:] * X2[i,:,k])
                
print('Y2:\n',Y2, Y2.shape)  # (1, 2, 2)

X1:
 [[[0 1 2]
  [3 4 5]]]
X2:
 [[[0 1]
  [2 3]
  [4 5]]]
Y1:
 [[[10 13]
  [28 40]]] (1, 2, 2)
Y2:
 [[[10. 13.]
  [28. 40.]]] (1, 2, 2)


## [3]  tf.keras.layers.Add
#### 입력 텐서들의 요소 간의 덧셈 연산을 수행하는 layer

<font size="4"> <pre> <b>  
        tf.keras.layers.Add(
            **kwargs
        )
</b> </pre>

In [13]:
input_shape = (1, 2, 3)
X1 = tf.random.normal(input_shape)
print('X1:\n',X1)
X2 = tf.random.normal(input_shape)
print('X2:\n',X2)
myadd = Add()
Y = myadd([X1, X2])
print('Y:\n',Y, Y.shape)  # (1, 2, 3)

X1:
 tf.Tensor(
[[[-0.24110962  0.06747787  0.32457784]
  [ 0.3141423  -0.6017014  -1.0139027 ]]], shape=(1, 2, 3), dtype=float32)
X2:
 tf.Tensor(
[[[ 0.41337535  0.4846839  -0.05236785]
  [-0.6784242  -0.0977253  -1.269239  ]]], shape=(1, 2, 3), dtype=float32)
Y:
 tf.Tensor(
[[[ 0.17226572  0.55216175  0.27221   ]
  [-0.3642819  -0.69942665 -2.2831416 ]]], shape=(1, 2, 3), dtype=float32) (1, 2, 3)


## [4]  tf.keras.layers.Concatenate
#### 입력 텐서들을 axis 값의 축방향으로 concatenate(합치기)을 수행하는 layer

<font size="4"> <pre> <b>  
        tf.keras.layers.Concatenate(
            axis=-1, **kwargs
        )
</b> </pre>

In [14]:
X1 = np.arange(1*2*3).reshape(1, 2, 3)
print('X1:\n',X1)
X2 = np.arange(1*2*3).reshape(1, 2, 3)
print('X2:\n',X2)


concat = Concatenate(axis=0)
Y0 = concat([X1, X2])
print('Y0:\n',Y0.numpy(), Y0.shape)  # (2, 2, 3)

concat = Concatenate(axis=1)
Y1 = concat([X1, X2])
print('Y1:\n',Y1.numpy(), Y1.shape)  # (1, 4, 3)

concat = Concatenate(axis=2)
Y2 = concat([X1, X2])
print('Y2:\n',Y2.numpy(), Y2.shape)  # (1, 2, 6)

concat = Concatenate(axis=-1)  # -1: 마지막 축 , axis=2 와 동일한 결과
Y3 = concat([X1, X2])
print('Y3:\n',Y3.numpy(), Y3.shape)  # (1, 2, 6)

X1:
 [[[0 1 2]
  [3 4 5]]]
X2:
 [[[0 1 2]
  [3 4 5]]]
Y0:
 [[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]] (2, 2, 3)
Y1:
 [[[0 1 2]
  [3 4 5]
  [0 1 2]
  [3 4 5]]] (1, 4, 3)
Y2:
 [[[0 1 2 0 1 2]
  [3 4 5 3 4 5]]] (1, 2, 6)
Y3:
 [[[0 1 2 0 1 2]
  [3 4 5 3 4 5]]] (1, 2, 6)


In [15]:
X1 = tf.keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
print('X1:\n',X1.shape)
X2 = tf.keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))
print('X2:\n',X2.shape)
concat = Concatenate()  # axis 생략시 기본값은 -1
Y = concat([X1, X2])  
print('Y:\n',Y.shape)  # (5,16)

X1:
 (5, 8)
X2:
 (5, 8)
Y:
 (5, 16)


## [5]  tf.keras.layers.Activation
#### 활성화 함수를 사용하여 출력하는 layer

<font size="4"> <pre> <b>  
        tf.keras.layers.Activation(
            activation, **kwargs
        )
</b> </pre>

In [16]:
X = np.array([-3.2,-1.1,0.1,1.3,2.3,5.2]).reshape(1,3,-1).astype('float32')
print('X:\n',X,X.shape)
layer = Activation('softmax')
Y = layer(X)
print('Y:\n',Y.numpy(), Y.shape)  # (1, 3, 2)

X:
 [[[-3.2 -1.1]
  [ 0.1  1.3]
  [ 2.3  5.2]]] (1, 3, 2)
Y:
 [[[0.10909683 0.8909032 ]
  [0.23147523 0.7685248 ]
  [0.05215357 0.9478465 ]]] (1, 3, 2)


In [17]:
X = np.array([-3.0, -1.0, 0.0, 1.5,2.0]).astype('float32')
layer = Activation('relu')
Y = layer(X)
print('Y: ',Y.numpy())  # relu: 0 이하는 0, 0보다 큰 값은 그대로 출력

Y:  [0.  0.  0.  1.5 2. ]


In [18]:
X = np.array([-3.0, -1.0, 0.0, 1.5,2.0]).astype('float32')
layer = Activation('sigmoid')
Y = layer(X)
print('Y: ',Y.numpy())  

Y:  [0.04742587 0.26894143 0.5        0.81757444 0.8807971 ]
