In [1]:
import tensorflow as tf
tf.__version__

'2.0.0'

# Keras Basic
### * Sequential Layer 의 주요 레이어 정리 
#### [1]  Dense Layer : Fully Connected Layer, layer의 입력과 출력 사이에 있는 모든 뉴런이 서로 연결 되는 Layer
#### [2]  Flatten Layer : 다차원(4차원)을 2차원으로 축소하여 FC Layer에 전달한다
#### [3]  Conv2D Layer : 이미지 특징을 추출하는 Convolution Layer 
#### [4]  MaxPool2D Layer : 중요 데이터(값이 큰 데이터)를 subsampling 하는 Layer
#### [5]  Dropout Layer : 학습시 신경망의 과적합을 막기위해 일부 뉴런을 제거하는 Layer

### [1] Dense Layer

In [2]:
# keras_basic

import tensorflow as tf
import numpy as np

# from tensorflow.keras import Sequential,Dense,...
# from keras import seq
# Sequential()

x_train = [1.0, 2.0, 3.0, 4.0, 5.0]   # (5,) 
y_train = [1.1, 2.2, 3.3, 4.4, 5.5]   # (5,) 

# model = tf.keras.Sequential()
# model.add(tf.keras.layers.Dense())
# model.add(t.keras.layers.Dense(units=1))


model = tf.keras.Sequential([
    # (?,1) * (1,7) = (?,7)   , Param :14 (W:7, b:7)
    # (5,1) * (1,7) = (5,7)   , Param :14 (W:7, b:7)
    tf.keras.layers.Dense(units=7, activation='relu', input_shape=(1,)), # input data의 shape을 (?,1) 
    
    # (?,7) * (7,1) = (?,1)   , Pram : 8  (W:7, b:1)
    # (5,7) * (7,1) = (5,1)   , Pram : 8  (W:7, b:1)
    tf.keras.layers.Dense(units=1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.01), loss='mse')

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 7)                 14        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 8         
Total params: 22
Trainable params: 22
Non-trainable params: 0
_________________________________________________________________


In [3]:
model.fit(x_train, y_train, epochs=100)

Train on 5 samples
Epoch 1/100
5/5 [==============================] - 1s 157ms/sample - loss: 16.6922
Epoch 2/100
5/5 [==============================] - 0s 3ms/sample - loss: 16.2386
Epoch 3/100
5/5 [==============================] - 0s 3ms/sample - loss: 15.8122
Epoch 4/100
5/5 [==============================] - 0s 3ms/sample - loss: 15.4126
Epoch 5/100
5/5 [==============================] - 0s 2ms/sample - loss: 15.0393
Epoch 6/100
5/5 [==============================] - 0s 2ms/sample - loss: 14.6915
Epoch 7/100
5/5 [==============================] - 0s 2ms/sample - loss: 14.3687
Epoch 8/100
5/5 [==============================] - 0s 2ms/sample - loss: 14.0694
Epoch 9/100
5/5 [==============================] - 0s 1ms/sample - loss: 13.7941
Epoch 10/100
5/5 [==============================] - 0s 4ms/sample - loss: 13.5448
Epoch 11/100
5/5 [==============================] - 0s 2ms/sample - loss: 13.3195
Epoch 12/100
5/5 [==============================] - 0s 2ms/sample - loss: 13.1082
Epoc

In [4]:
model.predict(x_train)

array([[1.8189552],
       [2.675808 ],
       [3.5326607],
       [4.3895135],
       [5.2463665]], dtype=float32)

In [5]:
model.evaluate(x_train,y_train)

5/1 [======================================================================================================================================================] - 0s 18ms/sample - loss: 0.1724


0.17237213253974915

In [6]:
# X,Y input data 
x_train = np.array([[1.0,   2.0,  3.0,  4.0,  5.0],
                    [6.0,   7.0,  8.0,  9.0, 10.0],
                    [11.0, 12.0, 13.0, 14.0, 15.0]])  # (3,5)
                    
                    
y_train = np.array([[1.1,   2.2,  3.3,  4.4,  5.5],
                    [6.1,   7.2,  8.3,  9.4, 10.5],
                    [11.1, 12.2, 13.3, 14.4, 15.5]]) # (3,5)

model = tf.keras.Sequential([
    # (3,1) * (1,100) = (3,100)   , Param :200 (W:1*100, b:100)
    # tf.keras.layers.Dense(units=100, activation='relu', input_shape=(1,)), # input data의 shape을 (?,1) 

    # (3,5) * (5,100) = (3,100)   , Param :600 (W:5*100, b:100)
    tf.keras.layers.Dense(units=100, activation='relu', input_shape=(5,)), # input data의 shape을 (?,5) 

    
    # (3,100) * (100,50) = (3,50)   , Param : 5050 (W:100*50, b:50)
    tf.keras.layers.Dense(units=50, activation='relu' ), 
    
    # (3,50) * (50,25) = (3,25)   , Param : 5050 (W:50*25, b:25)
    tf.keras.layers.Dense(units=25, activation='relu' ),
    
    # (3,25) * (25,5) = (3,5)   , Param : 130 (W:25*5, b:5)
    tf.keras.layers.Dense(units=5 , activation='relu' ),
    
#     # (3,5) * (5,1) = (3,1)   , Pram : 6  (W:5*1, b:1)
#     tf.keras.layers.Dense(units=1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.01), loss='mse')

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 100)               600       
_________________________________________________________________
dense_3 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_4 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 130       
Total params: 7,055
Trainable params: 7,055
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.fit(x_train, y_train, epochs=100)

Train on 3 samples
Epoch 1/100
3/3 [==============================] - 1s 179ms/sample - loss: 76.4652
Epoch 2/100
3/3 [==============================] - 0s 665us/sample - loss: 57.5874
Epoch 3/100
3/3 [==============================] - 0s 665us/sample - loss: 38.4393
Epoch 4/100
3/3 [==============================] - 0s 1ms/sample - loss: 26.0011
Epoch 5/100
3/3 [==============================] - 0s 665us/sample - loss: 32.3374
Epoch 6/100
3/3 [==============================] - 0s 1ms/sample - loss: 36.6849
Epoch 7/100
3/3 [==============================] - 0s 998us/sample - loss: 31.2214
Epoch 8/100
3/3 [==============================] - 0s 998us/sample - loss: 26.5416
Epoch 9/100
3/3 [==============================] - 0s 665us/sample - loss: 25.7046
Epoch 10/100
3/3 [==============================] - 0s 998us/sample - loss: 26.9832
Epoch 11/100
3/3 [==============================] - 0s 998us/sample - loss: 28.4095
Epoch 12/100
3/3 [==============================] - 0s 3ms/sample - lo

Epoch 99/100
3/3 [==============================] - 0s 998us/sample - loss: 24.4948
Epoch 100/100
3/3 [==============================] - 0s 997us/sample - loss: 24.4941


In [8]:
model.predict(x_train)

array([[ 0.       ,  0.       ,  3.6420217,  4.1769757,  5.3974295],
       [ 0.       ,  0.       ,  8.357432 ,  9.351834 , 10.449328 ],
       [ 0.       ,  0.       , 13.102687 , 14.531496 , 15.586285 ]],
      dtype=float32)

In [9]:
model.evaluate(x_train,y_train)

3/1 [==========================================================================================] - 0s 60ms/sample - loss: 24.4933


24.49327278137207

 ### [2] Flatten Layer

In [10]:
# 4차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28*10).reshape(1000,28,28,10).astype(np.float32)
print(data.shape) # (None, 28, 28, 10)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (None, 28*28*10) = (None,7840)

(1000, 28, 28, 10)
(1000, 7840)


In [11]:
# 3차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28).reshape(1000,28,28).astype(np.float32)
print(data.shape) # (None, 28, 28)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (None, 28*28) = (None,784)

(1000, 28, 28)
(1000, 784)


In [12]:
# 2차원 데이터는 그대로 FC Layer에 전달
data = np.arange(28*28).reshape(28,28).astype(np.float32)
print(data.shape) # (28, 28)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (28,28)

(28, 28)
(28, 28)


### [3] Dropout Layer

In [13]:
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout
# The Dropout layer randomly sets input units to 0 with a frequency of rate 
# at each step during training time, which helps prevent overfitting. 
# Inputs not set to 0 are scaled up by 1/(1 - rate) such that the sum over all inputs is unchanged.

# Note that the Dropout layer only applies when training is set to True such that
# no values are dropped during inference. When using model.fit, training will be
# appropriately set to True automatically, and in other contexts, you can set 
# the kwarg explicitly to True when calling the layer.

# (This is in contrast to setting trainable=False for a Dropout layer.
# trainable does not affect the layer's behavior, as Dropout does not have any 
# variables/weights that can be frozen during training.)

In [14]:
# 신버전 keras dropout

tf.random.set_seed(0)

layer = tf.keras.layers.Dropout(0.3, input_shape=(2,)) # 0.3, 0.5 
data = np.arange(10).reshape(5, 2).astype(np.float32)
print(data)
outputs = layer(data, training=True)  # model.fit()호출 시는  학습모드로 training=True가 되어 dropuout 적용
                                # model.evaluate() 호출 시는 예측모드로 False가 되어 dropuout이 수행되지 않음
print(outputs)
print(data * 1/(1 - 0.3)) # 데이터의 30%는 0으로 나머지 데이터는  1/(1-0.3)으로 곱하여 scaled up된다

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
tf.Tensor(
[[ 0.         0.       ]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.1428576]
 [ 8.571428  10.       ]
 [11.428572   0.       ]], shape=(5, 2), dtype=float32)
[[ 0.         1.4285715]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.142857 ]
 [ 8.571428  10.       ]
 [11.428572  12.857143 ]]


In [15]:
# 구버전 dropout

tf.random.set_seed(0)

data = np.arange(10).reshape(5, 2).astype(np.float32)
# @tf.function
def layer1(X):
    return tf.nn.dropout(X, rate=0.3)
print(layer1(data))

tf.Tensor(
[[ 0.         0.       ]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.1428576]
 [ 8.571428  10.       ]
 [11.428572   0.       ]], shape=(5, 2), dtype=float32)
