## RNN(Recurrent Neural Network) : 순환 신경망
#### 순서가 있는 시퀀스 데이터, time series data(시계열 데이터)를 입력하여 예측

### * RNN 주요 레이어 종류
#### (1) SimpleRNN
#### (2) LSTM(Long short Term Memory)
#### (3) GRU(Gated Recurent Unit)

In [1]:
# rnn_basic

import tensorflow as tf
import numpy as np


In [2]:
# Sequence data
X = np.array([[0,1,2,3],
              [1,2,3,4],
              [2,3,4,5],
              [3,4,5,6],
              [4,5,6,7],
              [5,6,7,8]],dtype=np.float32)

x_data = tf.reshape(X,(-1,4,1))  # (6,4,1)

y_data = np.array([4,5,6,7,8,9],dtype=np.float32)

print(x_data.shape,y_data.shape)
# print(type(x_data),type(y_data))

(6, 4, 1) (6,)


### [1] SimpleRNN
#### 가장 간단한 형태의 RNN 

In [3]:
# RNN 순환 신경망 구현  : SimpleRNN
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=300, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.SimpleRNN(units=300),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 4, 300)            90600     
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 300)               180300    
_________________________________________________________________
dense (Dense)                (None, 1)                 301       
Total params: 271,201
Trainable params: 271,201
Non-trainable params: 0
_________________________________________________________________


In [4]:
# 학습 및 예측
model.fit(x_data, y_data, epochs=100, verbose=0)
print(model.predict(x_data))

[[4.0131583]
 [4.955261 ]
 [5.9661775]
 [7.061049 ]
 [8.074243 ]
 [8.905968 ]]


In [5]:
# 학습되지 않은 입력 데이터에 대한 예측 결과
print(model.predict(np.array([[[6.],[7.],[8.],[9.]]])))
print(model.predict(np.array([[[-1.],[0.],[1.],[2.]]])))

[[9.52977]]
[[1.060151]]


### [2] LSTM(Long short Term Memory)
#### 입력 데이터와 출력 사이의 거리가 멀어질수로 연관 관계가 적어진다(Long Term Dependency,장기의존성 문제)
#### LSTM은 장기 의존성 문제를 해결하기 위해 출력값외에 셀상태(cell state)값을 출력함

In [6]:
# RNN 순환 신경망 구현  : LSTM
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(units=300, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.LSTM(units=300),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 4, 300)            362400    
_________________________________________________________________
lstm_1 (LSTM)                (None, 300)               721200    
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 301       
Total params: 1,083,901
Trainable params: 1,083,901
Non-trainable params: 0
_________________________________________________________________


In [7]:
# 학습 및 예측
model.fit(x_data, y_data, epochs=100, verbose=0)
print(model.predict(x_data))

[[3.378223 ]
 [5.1073303]
 [6.3818083]
 [7.3091574]
 [7.994758 ]
 [8.511158 ]]


In [8]:
# 학습되지 않은 입력 데이터에 대한 예측 결과
print(model.predict(np.array([[[6.],[7.],[8.],[9.]]])))
print(model.predict(np.array([[[-1.],[0.],[1.],[2.]]])))

[[8.90656]]
[[1.2503904]]


### [3] GRU(Gated Recurent Unit)
#### 뉴욕대 조경현 교수 등이 제안, LSTM보다 구조가 간단하고 성능이 우수

In [9]:
# RNN 순환 신경망 구현  : GRU
model = tf.keras.Sequential([
    tf.keras.layers.GRU(units=300, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.GRU(units=300),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
gru (GRU)                    (None, 4, 300)            272700    
_________________________________________________________________
gru_1 (GRU)                  (None, 300)               541800    
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 301       
Total params: 814,801
Trainable params: 814,801
Non-trainable params: 0
_________________________________________________________________


In [10]:
# 학습 및 예측
model.fit(x_data, y_data, epochs=100, verbose=0)
print(model.predict(x_data))

[[3.6418889]
 [5.020134 ]
 [6.203804 ]
 [7.2003284]
 [8.0281105]
 [8.709969 ]]


In [11]:
# 학습되지 않은 입력 데이터에 대한 예측 결과
print(model.predict(np.array([[[6.],[7.],[8.],[9.]]])))
print(model.predict(np.array([[[-1.],[0.],[1.],[2.]]])))

[[9.269005]]
[[2.08115]]


In [12]:
# RNN 사용 단어 학습 예측

In [13]:
# idx2char = ['h','i','e','l','o'] # 문자를 인덱스로 접근 가능
idx2char = ['a','b','c','d','e','f','g'] # 문자를 인덱스로 접근 가능

# x_data = np.array([0,1,0,2,3,3]) # 'hihell', (6,)
# y_data = np.array([1,0,2,3,3,4]) # 'ihello'  (6,)

x_data = np.array([[0,1,2,3,4,5]]) # 'abcdef', (1,6)
y_data = np.array([[1,2,3,4,5,6]]) # 'bcdefg'  (1,6)

x_one_hot = tf.one_hot(x_data,6)  # (6,6)
x_data = tf.reshape(x_one_hot,(-1,6,6))  # (1,6,6)
print(x_data.shape)
print(x_data)

(1, 6, 6)
tf.Tensor(
[[[1. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 1.]]], shape=(1, 6, 6), dtype=float32)


In [14]:
model = tf.keras.Sequential([
#     tf.keras.layers.SimpleRNN(units=30, return_sequences=True, input_shape=[5,1]),
#     tf.keras.layers.SimpleRNN(units=30),
#     tf.keras.layers.LSTM(units=30, return_sequences=True, input_shape=[5,1]),
#     tf.keras.layers.LSTM(units=30),
    tf.keras.layers.LSTM(units=1024, return_sequences=True, input_shape=[6,6]),
    tf.keras.layers.LSTM(units=512, return_sequences=True),
    tf.keras.layers.LSTM(units=512, return_sequences=True),
    tf.keras.layers.LSTM(units=256, return_sequences=True),
    tf.keras.layers.LSTM(units=256, return_sequences=True),
    tf.keras.layers.LSTM(units=128, return_sequences=True),
    tf.keras.layers.LSTM(units=128, return_sequences=True),
    tf.keras.layers.LSTM(units=64, return_sequences=True),
    tf.keras.layers.LSTM(units=64, return_sequences=True),
    tf.keras.layers.LSTM(units=32, return_sequences=True),
    tf.keras.layers.LSTM(units=32),
    tf.keras.layers.Dense(6)
])

model.compile(optimizer='adam', loss='mse',metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 6, 1024)           4222976   
_________________________________________________________________
lstm_3 (LSTM)                (None, 6, 512)            3147776   
_________________________________________________________________
lstm_4 (LSTM)                (None, 6, 512)            2099200   
_________________________________________________________________
lstm_5 (LSTM)                (None, 6, 256)            787456    
_________________________________________________________________
lstm_6 (LSTM)                (None, 6, 256)            525312    
_________________________________________________________________
lstm_7 (LSTM)                (None, 6, 128)            197120    
_________________________________________________________________
lstm_8 (LSTM)                (None, 6, 128)           

In [15]:
# 학습 및 예측
model.fit(x_data, y_data, epochs=100, verbose=0)

In [16]:
pred = model.predict(x_data).astype(np.int32)
print(pred)

[[1 1 2 3 4 5]]


In [17]:
x_data,y_data

(<tf.Tensor: id=20127, shape=(1, 6, 6), dtype=float32, numpy=
 array([[[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 1.]]], dtype=float32)>,
 array([[1, 2, 3, 4, 5, 6]]))