### 미니배치 버전 파이썬 구현

In [3]:
import numpy as np

X = np.random.rand(10,2)
X

array([[0.51207176, 0.07482727],
       [0.05977375, 0.03501587],
       [0.19901423, 0.29235501],
       [0.64761183, 0.87246631],
       [0.56884365, 0.81995161],
       [0.29455914, 0.02447365],
       [0.7331866 , 0.46423448],
       [0.73163077, 0.89479288],
       [0.127178  , 0.07522481],
       [0.40066274, 0.90792202]])

In [4]:
W1 = np.random.rand(2,4)
W1

array([[0.07375378, 0.68886511, 0.16210787, 0.43783836],
       [0.32199162, 0.17518231, 0.43824421, 0.00275161]])

In [6]:
b1 = np.random.rand(4)
b1

array([0.30364394, 0.30572006, 0.13531587, 0.82646522])

In [7]:
H = np.matmul(X,W1) + b1
H

array([[0.36550492, 0.67157685, 0.25111935, 1.05087578],
       [0.31932729, 0.35303028, 0.16035116, 0.85273281],
       [0.41245786, 0.49402945, 0.29570054, 0.91440573],
       [0.6323346 , 0.90467792, 0.62265216, 1.11241521],
       [0.60961586, 0.84121763, 0.58686895, 1.07778298],
       [0.3332491 , 0.51291893, 0.19379166, 0.95550185],
       [0.50719883, 0.8921124 , 0.45761926, 1.14875983],
       [0.64572028, 0.96646686, 0.64605678, 1.14926336],
       [0.33724556, 0.40650661, 0.18889926, 0.88235562],
       [0.62553762, 0.74077453, 0.59815803, 1.00438898]])