# Repeat 노드

In [9]:
import numpy as np

# 순전파

D = 8
N = 7
x = np.random.rand(1,D)  # (1,8)
# x = np.random.rand(D,).reshape(1,-1)  # (1,8)
print(x,x.shape)
print('-'*70)

y = np.repeat(x,N,axis=0)  # 수직(행) 방향, axis=0
print(y,y.shape)   # (7, 8)

[[0.76611644 0.90414271 0.71554915 0.24844669 0.43864523 0.14826477
  0.74384309 0.93119903]] (1, 8)
----------------------------------------------------------------------
[[0.76611644 0.90414271 0.71554915 0.24844669 0.43864523 0.14826477
  0.74384309 0.93119903]
 [0.76611644 0.90414271 0.71554915 0.24844669 0.43864523 0.14826477
  0.74384309 0.93119903]
 [0.76611644 0.90414271 0.71554915 0.24844669 0.43864523 0.14826477
  0.74384309 0.93119903]
 [0.76611644 0.90414271 0.71554915 0.24844669 0.43864523 0.14826477
  0.74384309 0.93119903]
 [0.76611644 0.90414271 0.71554915 0.24844669 0.43864523 0.14826477
  0.74384309 0.93119903]
 [0.76611644 0.90414271 0.71554915 0.24844669 0.43864523 0.14826477
  0.74384309 0.93119903]
 [0.76611644 0.90414271 0.71554915 0.24844669 0.43864523 0.14826477
  0.74384309 0.93119903]] (7, 8)


In [15]:
# 역전파 : sum
dy = np.random.rand(N,D)
print(dy,dy.shape)  # (7, 8)
print('-'*70)
dx = np.sum(dy,axis=0,keepdims=True)  # 수직방향 합, keepdims=True이면 2차원, False이면 1차원
print(dx,dx.shape)  # (1,8)

[[0.20362801 0.26080154 0.5182651  0.10072677 0.17850626 0.19440048
  0.31263453 0.2071148 ]
 [0.55234531 0.16317744 0.80868443 0.36993564 0.83312898 0.34418948
  0.25711844 0.96428303]
 [0.52373319 0.80469014 0.33145703 0.36908858 0.19843052 0.11008169
  0.4928258  0.56698851]
 [0.02203085 0.75178356 0.05012774 0.14835484 0.42941561 0.1203592
  0.75711643 0.78159995]
 [0.89597571 0.76868551 0.24050051 0.2552415  0.87891958 0.52830051
  0.70636274 0.03637929]
 [0.45567981 0.81827792 0.46349572 0.42247639 0.63646181 0.7940991
  0.05522526 0.99218557]
 [0.27999853 0.7175891  0.48254528 0.72441589 0.92223228 0.67968678
  0.43028787 0.09176965]] (7, 8)
----------------------------------------------------------------------
[[2.93339141 4.28500523 2.89507581 2.39023962 4.07709504 2.77111725
  3.01157107 3.64032079]] (1, 8)


In [18]:
a = np.array([[1,2,3,4]])
np.sum(a, keepdims=True) # 2차원 유지

array([[10]])

### Sum 노드

In [22]:
# 순전파

D,N = 8,7
x = np.random.rand(N,D) 
print(x,x.shape)  # (7,8)
print('-'*70)

y = np.sum(x,axis=0,keepdims=True)  # 수직방향 합, keepdims=True이면 2차원, False이면 1차원
print(y,y.shape)

[[3.79719447e-01 2.89143465e-01 7.04977394e-02 7.63135395e-01
  4.27156570e-01 1.57528661e-02 6.41675246e-01 7.20005589e-01]
 [2.30646915e-01 7.90785370e-01 4.89102124e-01 3.24148037e-01
  1.33341362e-01 5.97896604e-01 2.16614468e-01 3.29477912e-01]
 [3.63402720e-01 8.82308986e-01 8.91899498e-01 8.75732665e-01
  3.81500100e-01 2.89336591e-01 9.61217550e-01 6.83036529e-01]
 [9.57922382e-01 1.97912949e-02 1.52029536e-01 6.06539471e-03
  6.75549648e-01 5.41589364e-01 9.56597794e-02 5.31200418e-01]
 [8.45335710e-01 8.56595885e-01 3.36889136e-01 8.19701811e-04
  3.28429073e-01 8.76531999e-01 1.72423460e-01 5.73582237e-01]
 [7.93269692e-01 2.72208798e-01 7.51347290e-01 2.16618124e-01
  2.45037886e-01 1.49566798e-01 4.52127701e-01 1.27163721e-01]
 [1.64015354e-01 5.51279127e-01 6.09225832e-01 4.18912329e-01
  3.41971498e-01 6.29115835e-01 6.33135908e-01 8.57293913e-01]] (7, 8)
----------------------------------------------------------------------
[[3.73431222 3.66211293 3.30099115 2.60543165 

In [23]:
# 역전파

dy = np.random.rand(1,D)  # (1,8)
print(dy,dy.shape)
print('-'*70)

dx = np.repeat(dy,N,axis=0)  # 수직(행) 방향, axis=0
print(dx,dx.shape)   # (7, 8)

[[0.89736847 0.13357699 0.79104903 0.34191964 0.02839419 0.31278654
  0.43025854 0.64958187]] (1, 8)
----------------------------------------------------------------------
[[0.89736847 0.13357699 0.79104903 0.34191964 0.02839419 0.31278654
  0.43025854 0.64958187]
 [0.89736847 0.13357699 0.79104903 0.34191964 0.02839419 0.31278654
  0.43025854 0.64958187]
 [0.89736847 0.13357699 0.79104903 0.34191964 0.02839419 0.31278654
  0.43025854 0.64958187]
 [0.89736847 0.13357699 0.79104903 0.34191964 0.02839419 0.31278654
  0.43025854 0.64958187]
 [0.89736847 0.13357699 0.79104903 0.34191964 0.02839419 0.31278654
  0.43025854 0.64958187]
 [0.89736847 0.13357699 0.79104903 0.34191964 0.02839419 0.31278654
  0.43025854 0.64958187]
 [0.89736847 0.13357699 0.79104903 0.34191964 0.02839419 0.31278654
  0.43025854 0.64958187]] (7, 8)


### MatMul 노드

In [24]:
class MatMul:
    def __init__(self,W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None
        
    def forward(self,x):
        W = self.params
        out = np.dot(x,W)
        self.x = x
        return out
        
    def backward(self,dout):
        W = self.params
        dx = np.dot(dout,W.T)
        dw = np.dot(self.x.T,dout)
        self.grads[0][...] = dw  # 깊은복사
        return dx

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(hex(id(a)),hex(id(b)))
a = b    # 얕은 복사
print(a)
print(hex(id(a)),hex(id(b)))
id(a) == id(b)

0x269e5ed8ad0 0x269e5ed3b20
[4 5 6]
0x269e5ed3b20 0x269e5ed3b20


True

In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a[...] = b  # 깊은 복사
print(a)
print(hex(id(a)),hex(id(b)))
id(a) == id(b)

[4 5 6]
0x269e5ed8ad0 0x269e5ed8260


False

In [31]:
# np.zeros_like
a = np.arange(12).reshape(3,4)
b = np.zeros_like(a)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 시그모이드 계층

In [32]:
class Sigmoid:
    def __init__(self):
        self.params, self.grads = [],[]
        self.out = None
        
    def forward(self,x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out
    
    def backward(self,dout):
        dx = dout*self.out*(1 - self.out)  # 공식 도출은 참고서적 참조
        return dx        

### Affine 계층 : MatMul 노드에 bias를 더한 계층,  X*W + b

In [33]:
class Affine:
    def __init__(self,W,b):
        self.params = [W,b]
        self.grads = [np.zeros_like(W),np_zeros_like(b)]
        self.x = None
        
    def forward(self,x):
        W , b = self.params
        out = np.dot(x,W) + b
        self.x = x
        return out
        
    def backward(self,dout):
        W, b = self.params
        dx = np.dot(dout,W.T)
        dw = np.dot(self.x.T,dout)
        db = np.sum(dout,axis=0)
        
        self.grads[0][...] = dw  # 깊은복사
        self.grads[1][...] = db  # 깊은복사
        
        return dx    

## Softmax with Loss 계층

In [35]:
class SotmaxWithLoss:
    def __init__(self):
        self.params,self.grads=[],[]
        self.y = None  # softmax의 출력값
        self.t = None  # 정답 레이블
        
    def softmax(self,x):
        if x.ndim == 2:
            x = x - x.max(axis=1, keepdims=True)  # nan출력을 방지
            x = np.exp(x)
            x /= x.sum(axis=1,keepdims=True)
        elif x.ndim == 1:
            x = x - np.max(x)
            x = np.exp(x) / np.sum(np.exp(x))
        return x  
    
    # https://smile2x.tistory.com/entry/softmax-crossentropy-%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC 
    def cross_entropy_error(self,y, t):  
        if y.ndim == 1:
            t = t.reshape(1, t.size)
            y = y.reshape(1, y.size)

        # 정답 데이터가 원핫 벡터일 경우 정답 레이블 인덱스로 변환
        if t.size == y.size:
            t = t.argmax(axis=1)

        batch_size = y.shape[0]

        return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size  # 1e-7은 log(0)으로 무한대가 나오는걸 방지
          
    
    def forward(self, x, t):
        self.t = t
        self.y = slef.softmax(x)

        # 정답 레이블이 원핫 벡터일 경우 정답의 인덱스로 변환
        if self.t.size == self.y.size:
            self.t = self.t.argmax(axis=1)
       
        loss = self.cross_entropy_error(self.y,self.t)
        return loss
    
    def backward(self,dout=1):
        batch_size = self.t.shape[0]
        
        # dx = (self.y - self.t)/batch_size  # 순수 Softmax계층 일경우
        dx = self.y.copy()
        dx[np.arange(batch_size), self.t] -= 1
        dx *= dout
        dx = dx / batch_size
        
        return dx       
        

In [36]:
# softmax 구현시에  지수값이 크면 오버플로발생으로 nan이 나오는 것을 방지하기 위해 입력 값의 촤대값을 빼주어 사용한다
a = np.array([1010,1000,990])
print(np.exp(a))    # [inf inf inf]  , 무한대 값, 오버플로우 발생
x = np.exp(a)/np.sum(np.exp(a))
print(x)  # [nan nan nan]

c = np.max(a)
print(a - c)
x2 = np.exp(a - c)/np.sum(np.exp(a - c))
print(x2)  # [9.99954600e-01 4.53978686e-05 2.06106005e-09]

[inf inf inf]
[nan nan nan]
[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


C:\ProgramData\Anaconda3\envs\tf20\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\envs\tf20\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in exp
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\envs\tf20\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


### 가중치 갱신

In [38]:
# 확률적 경사하강법(Stochastic Gradient Descent)
class SGD :
    def __init__(self,lr=0.01):
        self.lr = lr
        
    def update(self,params,grads):
        for i in range(len(params)):
            params[i] -= self.lr*grads[i]    

In [ ]:
class Adam:
    '''
    Adam (http://arxiv.org/abs/1412.6980v8)
    
    '''
    def __init__(self, lr=0.001, beta1=0.9, beta2=0.999):
        self.lr = lr
        self.beta1 = beta1
        self.beta2 = beta2
        self.iter = 0
        self.m = None
        self.v = None
        
    def update(self, params, grads):
        if self.m is None:
            self.m, self.v = [], []
            for param in params:
                self.m.append(np.zeros_like(param))
                self.v.append(np.zeros_like(param))
        
        self.iter += 1
        lr_t = self.lr * np.sqrt(1.0 - self.beta2**self.iter) / (1.0 - self.beta1**self.iter)

        for i in range(len(params)):
            self.m[i] += (1 - self.beta1) * (grads[i] - self.m[i])
            self.v[i] += (1 - self.beta2) * (grads[i]**2 - self.v[i])
            
            params[i] -= lr_t * self.m[i] / (np.sqrt(self.v[i]) + 1e-7)
            
# https://dalpo0814.tistory.com/29